#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

if ($argc !== 2) {
    echo "Usage: ./test <file>\n";
    echo "  ex.: ./test example/01-just-text.php\n";
    echo "  ex.: \n";
    exit;
}


/** @noinspection PhpIncludeInspection */
return require_once $argv[1];
